### ISSUE TITLE
Crashed after running several days owing to fetching google groups

### ISSUE THREAD

**Issue by hsluoyz** [the-open-agent/openagent#265]
See:

![image](https://user-images.githubusercontent.com/3787410/121448723-d3dd3b00-c9ca-11eb-846b-f1771268ac83.png)

```
Update forum info: hotInfo, update num: 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x1727baa]

goroutine 26 [running]:
github.com/casbin/google-groups-crawler.GoogleGroup.GetAllConversations(0xc0007ce6e0, 0x6, 0xc0008b6c00, 0x55a, 0x1e13000, 0xc000232140, 0x0, 0x0, 0x0, 0x0, ...)
	C:/GoPath/pkg/mod/github.com/casbin/google-groups-crawler@v0.1.1/group.go:31 +0x1aa
github.com/casbin/casnode/object.Node.SyncFromGoogleGroup(0xc000060c60, 0xb, 0xc000060c90, 0xb, 0xc0007ce680, 0x19, 0xc000844660, 0x2e, 0xc000290820, 0x41, ...)
	C:/github_repos/casnode/object/mailing_list.go:38 +0x205
github.com/casbin/casnode/object.SyncAllNodeFromGoogleGroup()
	C:/github_repos/casnode/object/mailing_list.go:134 +0x1e5
github.com/casbin/casnode/object.AutoSyncGoogleGroup()
	C:/github_repos/casnode/object/mailing_list.go:119 +0x4a
created by github.com/casbin/casnode/object.InitForumBasicInfo
	C:/github_repos/casnode/object/basic.go:43 +0xb2

Process finished with the exit code 2
```

**Comment by hsluoyz** [comment]
@Kininaru

**Comment by keainye** [comment]
@hsluoyz 
I will make a pr to the crawler this noon.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/268
